<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-11-05T15:52:53 CLST" name="Suite" finished-at="2019-11-05T15:57:23 CLST" duration-ms="269950">
    <groups>
    </groups>
    <test started-at="2019-11-05T15:52:53 CLST" name="Test" finished-at="2019-11-05T15:57:23 CLST" duration-ms="269950">
      <class name="cl.bcs.application.suite.execute.RVExecute">
        <test-method is-config="true" signature="startReport()[pri:0, instance:cl.bcs.application.suite.execute.RVExecute@428640fa]" started-at="2019-11-05T15:52:52 CLST" name="startReport" finished-at="2019-11-05T15:52:53 CLST" duration-ms="604" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startReport -->
        <test-method signature="variacion1()[pri:1, instance:cl.bcs.application.suite.execute.RVExecute@428640fa]" started-at="2019-11-05T15:52:53 CLST" name="variacion1" finished-at="2019-11-05T15:57:23 CLST" duration-ms="269934" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at cl.bcs.application.suite.execute.RVExecute.variacion1(RVExecute.java:40)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- variacion1 -->
      </class> <!-- cl.bcs.application.suite.execute.RVExecute -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
